it-projects-llc/odoo-saas-tools

saas_portal/__openerp__.py, saas_portal/controllers/main.py, saas_portal_signup/__init__.py, saas_portal_signup/__openerp__.py, saas_portal_signup/controllers/__init__.py, saas_portal_signup/controllers/main.py, saas_portal_signup/views/signup.xml
I created the saas_portal_signup module as we talk. Are you going to create the saas_portal_start?
=> separate features for sign up in a new module

saas_portal/controllers/main.py, saas_portal/models/saas_portal.py, saas_portal/models/wizard.py, saas_portal_signup/__openerp__.py, saas_portal_signup/controllers/main.py, saas_portal_signup/views/signup.xml, saas_portal_start/controllers/main.py, saas_portal_start/static/src/js/main.js
Now in saas_portal_start I use the first confirmed saas_portal.plan to create a new client. Maybe we need something better.
=> Fixes in saas_portal_start and saas_portal_signup

saas_sysadmin_route53/models/saas_sysdamin_route53.py
Make sure hosted zone exists for server before
we attempt to create or modify DNS records for
a template db
=> [FIX] saas_sysadmin_route53

README.md, oauth_provider/models/oauth_provider.py, saas_client/models/res_user.py, saas_portal/controllers/main.py, saas_portal/models/saas_portal.py, saas_portal/models/wizard.py, saas_portal/views/saas_portal.xml, saas_portal_demo/controllers/main.py, saas_portal_templates/controllers/main.py, saas_pricing/__openerp__.py, saas_server/controllers/main.py, saas_server/models/saas_server.py
The update is not finished yet. Coming soon.
Also, it includes:
* fix #42 
* server-side database deleting
=> server-side database creating + instruction for API integration

saas_portal_sale/README.rst, saas_portal_sale/__init__.py, saas_portal_sale/__openerp__.py, saas_portal_sale/controllers.py, saas_portal_sale/templates.xml
https://www.it-projects.info/web#id=286&view_type=form&model=project.task&action=152&active_id=29
=> [ADD] saas_portal_sale

saas_base/models/saas_base.py, saas_client/models/ir_configparameter.py, saas_client/models/res_user.py, saas_portal/models/wizard.py, saas_portal/views/saas_portal.xml, saas_server/controllers/main.py, saas_server/models/saas_server.py, saas_server/views/saas_server.xml
https://www.it-projects.info/web#id=305&view_type=form&model=project.task&action=152&active_id=29
=> [ADD] suspended configuration option

saas_portal_sale_online/__openerp__.py
add website_sale_require_login in saas_portal_sale_online dependencies
=> [ADD] website_sale_require_login in deps

saas_portal/models/saas_portal.py
update template deletion to use delete_database_server and no need for self[0]
=> [IMP] update template deletion to use delete_database_server

saas_portal/models/wizard.py, saas_portal/views/saas_portal.xml
adds the ability to configure multiple databases at the same time
=> saas_portal: multi config databases

saas_server/models/saas_server.py
Wrapping call to registry.cursor() as client_cr fixes FATAL:  database "xxxxx" does not exist error
=> [FIX] OperationalError psycopg2 in connect

saas_server_backup_ftp/__openerp__.py, saas_server_backup_ftp/models/res_config.py, saas_server_backup_ftp/models/saas_server.py, saas_server_backup_rotate_s3/__openerp__.py, saas_server_backup_rotate_s3/models/saas_server.py, saas_server_backup_s3/models/saas_client.py, saas_sysadmin_route53/models/saas_sysdamin_route53.py
=> [FIX] change log level for import errors

saas.py, saas_portal/models/saas_portal.py, saas_server/controllers/main.py
=> [IMP] support for --db-filter=%d

saas.py, saas_portal/models/saas_portal.py
[FIX] create_template: use local_port
[IMP] add request url to error log
=> [FIX] saas.py: use local_port

saas_client/data/auth_oauth_data.xml, saas_server/data/auth_oauth_data.xml
=> [FIX] disable built-in provider_openerp instead of deleting one

saas_server/models/saas_server.py
https://github.com/it-projects-llc/odoo-saas-tools/commit/e51b27e590501359d7132fdc7466be0a59c4b73f
=> [FIX] clean  code and fix issue after

oauth_provider/__openerp__.py, oauth_provider/security/ir.model.access.csv, requirements.txt, saas_portal/__openerp__.py, saas_portal/security/ir.model.access.csv
=> [FIX] fix travis errors:

saas.py
[IMP] make --without-demo optional and False by default
=> [FIX] on database creation --workers must be zero

saas_server_backup_ftp/models/res_config.py, saas_server_backup_ftp/models/saas_server.py, saas_server_backup_ftp/views/res_config.xml
=> [IMP][8.0] add rsa key auth method

saas_portal/views/saas_portal.xml, saas_portal_portal/views/templates.xml, saas_server_backup_ftp/views/res_config.xml
* I could not test it for the moment. Is it possible to run this code in runbot to check there are no mistakes?
* the choice of icon is subjective as there are no correspondance between the two collections
=> Substitute icons GTP -> FA

saas.py
this is needed for docker installation, where odoo is running a the
moment of running odoo
=> [FIX] don't run odoo, if one is already running

oauth_provider/security/ir.model.access.csv, saas_portal/security/ir.model.access.csv, saas_portal_demo/security/ir.model.access.csv
Following models only accessible to employee user's group: - saas_portal_plan - oAuth_application
=> Fixportalperm (Fixes issue #402)

saas.py
we need it to use in docker installation with --network
=> [CI] saas.py: add default values for postgres

oauth_provider/security/ir.model.access.csv, saas_portal/security/ir.model.access.csv, saas_portal_demo/security/ir.model.access.csv
Hide SaaS main menu from portal user (Fixes issue #402) for odoo 9.0 version
=> [FIX] fix portal permission

saas.py
because in most cases the password is already changed (otherwise one can add
--drop-database option and start the process from scratch)
=> saas.py: don't try to change admin password if db already exists

404.html, _includes/footer.html, _includes/head.html, _includes/nav.html, _layouts/page.html, _layouts/post.html
username.github.io repositories, rather than for gh-pages branch
=> [FIX] add /odoo-saas-tools/ prefix, because original theme is made for

saas.py
environment variable to load odoo config, if --odoo-config is not specified
=> [CI] use separate param to specify master password + use OPENERP_SERVER

saas.py
Otherwise in docker environment the script can run another odoo if docker odoo
doesn't open the port in 3 second
=> [CI] saas.py: add --use-existed-odoo to wait infinitly for port

_posts/2017-06-06-fundraising-campaign.md
=> [DOC] fix spelling

saas_server/models/saas_server.py
=> [TEXT] clarify  error message

_posts/2017-06-06-fundraising-campaign.md
=> [DOC] update fundraising plan

requirements.txt
See issue #372
Added `simplejson` to requirements.txt so it can be installed automatically by pip (I'm doing an automated deployment, this makes it one command less, no reason to manually do `pip install simplejson`)
=> Added simplejson to requirements.txt

saas_portal/__openerp__.py, saas_portal/data/base_action_rule.xml, saas_portal/data/base_automation.xml, saas_portal/data/cron.xml, saas_portal/views/saas_portal.xml, saas_server/controllers/main.py, saas_server/models/saas_server.py
- With this revision, you can create base and server in V11
- You can create plan with template and all is ok.
I don't test all module / addons but will fix it when I need.
I think we need to add some tests
=> 11.0 migrate python3 and odoo 11

saas_portal/models/saas_portal.py
[FIX v11] saas_portal function: storage_usage_monitoring -> total_storage_limit = 0 -> no limit
- new conditions were added
=> [FIX v11] saas_portal function

saas_client/__init__.py, saas_client/http.py
Hi guys, the security.check(self.db, self.uid, self.password) has removed in this commit.So the check method in saas_client won't be called.
=> [FIX] Fix client suspended validation.

saas.py
Hi,
Allows to choose `--server-db-name` on `--plan-create` in **saas.py**.
Thanks!
=> [11.0] [IMP] saas.py: Allow to choose server on create plan

saas.py, saas_portal/models/saas_portal.py
Hi,
Allows to choose `--db-lang` in **saas.py**.
Thanks!
=> [11.0] [IMP] saas.py: Allow to choose DB language

saas.py
Hi,
Fixes `TypeError` in **saas.py** when doing `--help`
Thanks!
=> [11.0] [FIX] saas.py: Fix TypeError in help

saas_portal_demo/data/ir_cron.xml, saas_portal_demo/views/saas_portal_demo_templates.xml, saas_server_autodelete/data/ir_cron.xml
=> fix ir.cron job and portal view.

saas_portal/models/saas_portal.py
Improved code of  _compute_get_state compute method for the plan and fixed singleton issue.
Below is the screenshot, when I am clicked on synch client button in the plan it raised the error.
See the below traceback logs screenshot
Thanks
=> [IMP/FIX] Improved code of compute method fixed singleton issue.

saas_server_backup_s3/views/res_config.xml
Hello @yelizariev and @tarzan0820 
When I was trying to install module saas_server_backup_s3 in the fresh database it was raised XML issue, we trace it and fixed that.
Below is some screenshot, Please check it.
It was given traceback see the below screenshot. I fixed that and send pull request.
Kindly please check it.
Thank you.
=> [FIX] saas_server_backup_s3 : Fixed xml issue v11.

saas_client/models/res_config.py, saas_client/views/res_config.xml
=> [11.0] [FIX] saas_client: Fix SaaS section in general settings

saas_base/__manifest__.py, saas_client/__manifest__.py, saas_portal/__manifest__.py, saas_server/__manifest__.py
Hi,
I think saas_utils does nothing and saas_* should not depend on it.
Regards!
=> [11.0] [FIX] saas_base, saas_client, saas_portal, saas_server: Not depend on saas_utils
